version: "3.9"

services:
  db:
    image: postgres:17.1
    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: fitness
      POSTGRES_DB: fitness
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 10s
      retries: 5
      start_period: 5s

  ollama:
    image: ollama/ollama:latest
    volumes:
      - "ollama:/root/ollama"
    networks:
      - backend
    entrypoint: [ "/bin/sh", "-c", "ollama pull gemma3:1b-it-qat && ollama serve" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 30s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "50051:50051"

  workout-service:
    build:
      context: ./workout
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "50052:50052"

  llm-service:
    build:
      context: ./llm
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "50053:50053"

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  ollama:
