services:
  # PostgreSQL database
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fitness_tracker
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Ollama LLM server
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434" # default Ollama port

  # Go API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
      - ollama
    environment:
      # Web server port inside container
      PORT: 8080
      # Database connection string (internal host names)
      DATABASE_URL: postgres://postgres:postgres@db:5432/fitness_tracker?sslmode=disable
      # Example: base URL to reach Ollama service from API
      OLLAMA_BASE_URL: http://ollama:11434
    ports:
      - "8080:8080"

volumes:
  db-data:
  ollama-data:
